spring:
  zipkin:
    base-url: http://192.168.99.100:9411
  sleuth:
    sampler:
      # 全部监控
      percentage: 1.0
logging:
  level.com.github.bus: debug
#默认为false，如果想用断路由，要打开这个设置
feign:
  hystrix:
    enabled: true
#spring boot admin monitor
management:
  endpoints:
    web:
      exposure:
        include: '*'
      #跨域
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false
foo: hello world!