logging:
  level.com.github.bus: debug
spring:
  redis:
    # Redis服务器地址
    host: 192.168.0.6
    # Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    #password:
    # 连接超时时间（毫秒）
    #timeout: 0ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000ms
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
zuul:
  routes:
    api-example:
      path: /api-example/**
      serviceId: bus-example-service
    api-upms:
      path: /api-upms/**
      serviceId: bus-upms-service
security:
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:8763/bus-auth/oauth/token
      user-authorization-uri: http://127.0.0.1:8763/bus-auth/oauth/authorize
    resource:
      user-info-uri: http://127.0.0.1:8763/bus-auth/user
      prefer-token-info: true