spring:
    zipkin:
        base-url: http://192.168.99.100:9411
    sleuth:
        sampler:
            # 全部监控
            percentage: 1.0
    datasource:
        name: bus-upms-data
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
            #监控统计拦截的filters
            filters: stat
            driver-class-name: com.mysql.jdbc.Driver
            #基本属性
            url: jdbc:mysql://192.168.0.3:4306/bus-db-upms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=&useSSL=false
            username: dev
            password: manager001
            #配置初始化大小/最小/最大
            initial-size: 1
            min-idle: 1
            max-active: 20
            #获取连接等待超时时间
            max-wait: 60000
            #间隔多久进行一次检测，检测需要关闭的空闲连接
            time-between-eviction-runs-millis: 60000
            #一个连接在池中最小生存的时间
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
            pool-prepared-statements: false
            max-pool-prepared-statement-per-connection-size: 20

#mybatis
mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.gihub.bus.upms.model
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
    level.com.github.bus: debug
#默认为false，如果想用断路由，要打开这个设置
feign:
    hystrix:
        enabled: true
#spring boot admin monitor
management:
    endpoints:
        web:
            exposure:
                include: '*'
            #跨域
            cors:
                allowed-origins: "*"
                allowed-methods: "*"
    endpoint:
        health:
            show-details: ALWAYS
    security:
        enabled: false
