logging:
  level.com.github.bus: debug
#redis配置-单点模式
spring:
  redis:
    # Redis服务器地址
    host: 192.168.0.6
    # Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    #password:
    # 连接超时时间（毫秒）
    #timeout: 0ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000ms
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0